gallery/urls.py
from django.urls import path

from . import views

app_name = "gallery"
urlpatterns = [
    path('', views.index, name='index'),
    path('entry/<int:pk>', views.entry_pk, name='entry_pk'),
]

home/urls.py
from django.urls import path

from . import views

app_name = "home"
urlpatterns = [
    path('', views.index, name='index'),
]

kapno_cc/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('django_kapnoc/', include('django_kapnoc.urls')),
    path('', include('home.urls')),
    path('gallery/', include('gallery.urls')),
)

gallery/models.py
from django.db import models

from django_kapnoc.models import Image, Tag


class GalleryEntry(models.Model):
    image = models.ForeignKey(Image, on_delete=models.DO_NOTHING)
    label = models.CharField(max_length=255)
    description = models.TextField(blank=True, default="")
    parent = models.ForeignKey(
        'GalleryEntry', blank=True, null=True, on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)

    def __str__(self):
        return f'{self.label} (GalleryEntry)'

home/models.py
from django.db import models

# Create your models here.

gallery/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.utils.translation import gettext as _
from django.shortcuts import redirect
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse

from .models import GalleryEntry


def index(request):
    entries = GalleryEntry.objects.filter(parent=None)[:]
    context = {
        'title': _('Gallery'),
        'at_gallery_home': True,
        'entries': entries,
    }
    return render(request, 'gallery/index.html', context)


def entry_pk(request, pk):
    if pk == None:
        return redirect(index)
    try:
        elem = GalleryEntry.objects.get(pk=pk)
    except ObjectDoesNotExist:
        raise Http404(_('Gallery element does not exist'))
    entries = GalleryEntry.objects.filter(parent=pk)
    if entries.count() == 0:
        pass
    try:
        prev = elem.get_previous_by_created_at(parent=elem.parent)
    except ObjectDoesNotExist:
        prev = None
    try:
        next = elem.get_next_by_created_at(parent=elem.parent)
    except ObjectDoesNotExist:
        next = None
    context = {
        'title': _('Gallery') + ' - ' + elem.label,
        'elem': elem,
        'parent': elem.parent,
        'prev': prev,
        'next': next,
        'entries': entries,
    }
    return render(request, 'gallery/index.html', context)

home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.utils.translation import gettext as _


def index(request):
    context = {
        'title': _('Home'),
    }
    return render(request, 'home/index.html', context)

gallery/templates/gallery/index.html
{% extends 'base.html' %}
{% block 'contents' %}

{% load i18n %}
{% load thumbnail %}



<div class="row center-align">
    <div class="col s4">
        {% if prev %}
        <a class="btn green darken-2 flow-text"
            href="{% url 'gallery:entry_pk' prev.pk %}">{% trans "Previous: " %}{{ prev.label }}</a>
        {% endif %}
    </div>

    <div class="col s4">
        {% if parent %}
        <a class="btn green darken-2 flow-text"
            href="{% url 'gallery:entry_pk' parent.pk %}">{% trans "Back: " %}{{ parent.label }}</a>
        {% elif not at_gallery_home %}
        <a class="btn green darken-2 flow-text" href="{% url 'gallery:index'%}">{% trans "Back to Gallery Home" %}</a>
        {% endif %}
    </div>

    <div class="col s4">
        {% if next %}
        <a class="btn green darken-2 s2 flow-text"
            href="{% url 'gallery:entry_pk' next.pk %}">{% trans "Next: " %}{{ next.label }}</a>
        {% endif %}
    </div>
</div>


{% if elem %}
<div class="card">
    <div class="card-image">
        <img class="img-fluid card-img-top" src="{{ elem.image.image.url }}" alt="" />
        <span class="card-title">{{ elem.label }}</span>
    </div>

    <div class="card-content">
        <p>{{ elem.description }}</p>
    </div>
</div>
{% endif %}


<div class="row">
    {% for entry in entries %}
    <div class="col s3">
        <a href="{% url 'gallery:entry_pk' entry.pk %}">
            <div class="card small">
                <div class="card-image">
                    {% with img=entry.image.image|thumbnailer %}
                    <img class="img-fluid card-img-top" src="{{ img.medium_4_3.url }}" alt="" />
                    {% endwith %}
                    <span class="card-title">{{ entry.label }}</span>
                </div>

                <div class="card-content grey-text text-darken-4">
                    <p>{{ entry.description }}</p>
                </div>
            </div>
        </a>
    </div>
    {% endfor %}
</div>


{% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}
{% block 'contents' %}
<h1>aled</h1>
{% endblock %}

kapno_cc/templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">

    <title>{{title}} - kapno.cc</title>

    <link rel="icon" href="{% static 'favicon.ico' %}" />


    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
        media="screen,projection" />

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />


    <link rel="stylesheet" href="{% static 'style/global.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Roboto|Roboto+Mono&display=swap" rel="stylesheet" />
</head>

<body>


    <header>
        <nav class="nav-extended grey darken-4">
            <div class="container">
                <div class="nav-wrapper">
                    <a class="brand-logo center">kapno.cc</a>

                    <ul id="nav-mobile" class="right hide-on-med-and-down">
                        {% get_available_languages as LANGUAGES %}
                        {% for lang in LANGUAGES %}
                        <li>
                            <form action="{% url 'set_language' %}" method="post">
                                {% csrf_token %}
                                <input name="language" type="hidden" value="{{ lang.0 }}" />
                                <button class="btn-flat nav-link white-text" type="submit">
                                    {{ lang.0 }}
                                </button>
                            </form>
                        </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="divider green darken-2"></div>
                <div class="section"></div>

                <div class="nav-content">
                    <ul class="tabs tabs-transparent">
                        <li><a class="nav-link" href="{% url 'home:index' %}">{% trans "Home" %}</a></li>
                        <li><a class="nav-link" href="{% url 'gallery:index' %}">{% trans "Gallery" %}</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <!-- grey darken-4
        green darken-2 -->

    <main>
        <div class="container">

            <h5 class="center-align m2">{{title}}</h5>

            {% block 'contents' %}
            {% endblock %}

        </div>
    </main>

    <footer class="page-footer grey darken-4">
        <div class="container">
        </div>
    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</body>

</html>